---
version: '3.9'

services:
  runner:
    image: roslynos-github-runner:latest
    build:
      context: .
      args:
        RUNNER_VERSION: '2.297.0'
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}